# -*- coding: utf-8 -*-
"""Module_2Exam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/159qXAf1RV958x_WPTI5DzYd_1T7eJDXv
"""

#q1
for i in range(0,6):
  for j in range(1,i+1):
    if(i%2!=0):
      print("0",end=" ")
    else:  
     print("1",end =" ")
  print()

#q2
class Math:
  def set_data(self,a,b):
    self.a=a
    self.b=b
 
  def add(self,a,b):
    sum =a+b
    print(sum)
  def sub(self,a,b):
    s= a-b
    print("Difference of two number:",s)

  def mul(self,a,b):
    m =a*b
    print("product of two number:",m)
  def div(self,a,b):
    d = a/b 
    print("division of two number:",d)
obj=Math()
obj.set_data(12,10)
obj.add(10,12)
obj.sub(12,10)
obj.mul(12,10)
obj.div(12,10)

#Q3
arr=["zero","one","two","three","four","five","six","seven","eignt","nine"]
def number (n):
  if(n==0):
    return ""
  else: 
      a = arr[n%10]
      ans=number(int(n/10))+a+""
      return ans
n = int(input())
print(n)
print(end="")
print(number(n))

#Q4
p=100
rs=int(input("enter amount"))
r=rs*p
print(r)



#q5
s="twinkle"
b=""
for i in range(len(s)):
  if(i%2==0):
    b+=s[i]
b

#q6
s= (input("enter a string:"))
aph=digit=symbol=0
for i in range(len(s)):
  if(s[i].isalpha()):
    aph= aph+1
  elif(s[i].isdigit()):
    digit= digit+1  
  else:
    symbol= symbol+1  
print("total number of alph:",aph) 
print("total number of digit:",aph)    
print("total number of  symbol:",aph)

